services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./src:/src
    command: sh -c "poetry run python app.py"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:17
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data

  postgresql-test:
    image: postgres:17
    ports:
      - 5433:5432
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /var/cache/postgres_data_test:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - 5050:80
    depends_on:
      - postgresql
