services:
  # app:
  #   build:
  #     context: .
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./src:/src
  #   command: sh -c "poetry run python app.py"
  #   depends_on:
  #     - postgresql
  #   env_file:
  #     - ./.env

  postgres:
    image: postgres:17
    container_name: pg_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1245
      POSTGRES_DB: task_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
