"""remove responses id  in tickets table

Revision ID: 464ef4bfd206
Revises: ffee950cd865
Create Date: 2025-04-16 19:23:48.281162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '464ef4bfd206'
down_revision: Union[str, None] = 'ffee950cd865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tickets_responses_id_fkey', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'responses_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('responses_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('tickets_responses_id_fkey', 'tickets', 'responses', ['responses_id'], ['id'])
    # ### end Alembic commands ###
