"""update product table

Revision ID: a633fbdd9d79
Revises: f5f6db44d699
Create Date: 2025-04-20 17:15:29.848535

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a633fbdd9d79"
down_revision: Union[str, None] = "f5f6db44d699"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_products_name", table_name="products")
    op.create_index(
        op.f("ix_products_name"), "products", ["name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.create_index("ix_products_name", "products", ["name"], unique=False)
    # ### end Alembic commands ###
