"""add responses in tickets table

Revision ID: ffee950cd865
Revises: 4d459771d489
Create Date: 2025-04-16 19:12:11.957875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'ffee950cd865'
down_revision: Union[str, None] = '4d459771d489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('responses_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tickets', 'responses', ['responses_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'responses_id')
    # ### end Alembic commands ###
